### PR TITLE
Add support for AMQP 1.0 output

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Review by stalehd — APPROVED** [review]

**Comment by stalehd** [comment]
@lulf: Sorry for the late response -- I'll merge it RSN

**Comment by lulf** [comment]
Forgot to mention this, but the library used depends on a C library as well, it might complicate things. The library should be installable on the major Linux distros (https://qpid.apache.org/packages.html, as well as compilable on windows and mac), but I don't know if its possible to opt-in or opt-out dependencies in go.

**Comment by stalehd** [comment]
Hmmm. Might have to do some trickery to get it to compile. I'll have a look at it. The qpid docs are *slighly* fuzzy when it comes to macOS.

**Comment by lulf** [comment]
Great, thanks! The build dependencies are listed here: https://github.com/apache/qpid-proton/blob/master/INSTALL.md#dependencies

**Pull request merged**
